/**
 * TRAVEL MAPS - SCRIPT KHỞI TẠO CẤU TRÚC DATABASE & DỮ LIỆU CỐT LÕI
 * Rút gọn chỉ bao gồm:
 *  - Lệnh tạo tất cả các bảng (CREATE TABLE IF NOT EXISTS), View, Indexes, RLS
 *  - Dữ liệu tài khoản quản trị Admin Trùm (caophuocdanh@hotmail.com)
 *  - Dữ liệu 5 nhóm dịch vụ chuẩn
 *  - Dữ liệu 7 thẻ tags cơ bản
 *  - Dữ liệu đầy đủ 63 tỉnh thành Việt Nam
 * (Các địa điểm du lịch, review, chi tiêu mẫu người dùng tự nhập hoặc import từ file sqlsample.sql)
 */
export const CREATE_TABLE_SQL = `-- =============================================================================
-- TRAVEL MAPS - SCRIPT KHỞI TẠO CẤU TRÚC DATABASE & DỮ LIỆU CỐT LÕI (SCHEMA DDL)
-- =============================================================================
-- Hướng dẫn: Dán toàn bộ mã này vào Supabase SQL Editor và nhấn "Run".
-- Script bao gồm:
--  1. Các tiện ích mở rộng PostgreSQL (uuid-ossp, pgcrypto).
--  2. Toàn bộ câu lệnh CREATE TABLE (travel_users, travel_groups, travel_cities,
--     travel_locations, travel_location_details, travel_tags, travel_trips, ...)
--  3. View tổng hợp public.travel_places_view.
--  4. Chỉ mục tối ưu hiệu năng & Row Level Security (RLS) policies.
--  5. Dữ liệu mồi cần thiết: Tài khoản Admin Trùm, 5 Nhóm Dịch Vụ, 63 Tỉnh Thành VN.
-- (Các dữ liệu địa điểm, review, chi tiêu mẫu bạn có thể tự nhập hoặc import từ sqlsample.sql)
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- -----------------------------------------------------------------------------
-- 1. BẢNG NGƯỜI DÙNG & TÀI KHOẢN (travel_users)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.travel_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255),
  role VARCHAR(50) DEFAULT 'user',
  avatar_url TEXT,
  phone VARCHAR(50),
  status VARCHAR(50) DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- 2. BẢNG PHÂN NHÓM DỊCH VỤ (travel_groups)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.travel_groups (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  icon VARCHAR(50),
  badge_bg VARCHAR(100),
  marker_color VARCHAR(50),
  description TEXT,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- 3. BẢNG THÀNH PHỐ / TỈNH THÀNH (travel_cities)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.travel_cities (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  code VARCHAR(20),
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- 4. BẢNG ĐỊA ĐIỂM CỐT LÕI (travel_locations)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.travel_locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  group_id VARCHAR(50) REFERENCES public.travel_groups(id) ON DELETE SET NULL,
  city_id VARCHAR(50) REFERENCES public.travel_cities(id) ON DELETE SET NULL,
  category VARCHAR(100),
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  address TEXT NOT NULL,
  phone VARCHAR(50),
  contact VARCHAR(100),
  checked BOOLEAN DEFAULT FALSE,
  visited_at TIMESTAMPTZ,
  is_favorite BOOLEAN DEFAULT FALSE,
  is_deleted BOOLEAN DEFAULT FALSE,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- 5. BẢNG CHI TIẾT ĐỊA ĐIỂM (travel_location_details)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.travel_location_details (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id BIGINT UNIQUE REFERENCES public.travel_locations(id) ON DELETE CASCADE,
  rating NUMERIC(3, 1) DEFAULT 4.5,
  price_range VARCHAR(100),
  opening_hours VARCHAR(100),
  best_time_to_visit VARCHAR(255),
  notes TEXT,
  travel_tips TEXT,
  specialties TEXT,
  thumbnail_url TEXT,
  gallery_urls JSONB DEFAULT '[]'::jsonb,
  website_url TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tự động tương thích ngược: Chuyển đổi gallery_urls sang JSONB nếu bảng cũ đang lưu dạng TEXT[] hoặc ARRAY
DO $$ 
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
      AND table_name = 'travel_location_details' 
      AND column_name = 'gallery_urls' 
      AND (data_type = 'ARRAY' OR udt_name = '_text' OR udt_name = '_varchar')
  ) THEN
    ALTER TABLE public.travel_location_details 
      ALTER COLUMN gallery_urls DROP DEFAULT;
    ALTER TABLE public.travel_location_details 
      ALTER COLUMN gallery_urls TYPE JSONB USING COALESCE(to_jsonb(gallery_urls), '[]'::jsonb);
    ALTER TABLE public.travel_location_details 
      ALTER COLUMN gallery_urls SET DEFAULT '[]'::jsonb;
  END IF;
END $$;

-- -----------------------------------------------------------------------------
-- 6. BẢNG THẺ TAGS (travel_tags & travel_location_tags)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.travel_tags (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  color VARCHAR(50),
  icon VARCHAR(50),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.travel_location_tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id BIGINT REFERENCES public.travel_locations(id) ON DELETE CASCADE,
  tag_id VARCHAR(50) REFERENCES public.travel_tags(id) ON DELETE CASCADE,
  UNIQUE(location_id, tag_id)
);

-- -----------------------------------------------------------------------------
-- 7. BẢNG LỊCH TRÌNH CHUYẾN ĐI (travel_trips & travel_trip_stops)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.travel_trips (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id VARCHAR(100),
  user_email VARCHAR(255),
  user_name VARCHAR(255),
  title VARCHAR(255) NOT NULL,
  description TEXT,
  start_date DATE,
  end_date DATE,
  budget NUMERIC(15, 2) DEFAULT 0,
  cover_image TEXT,
  status VARCHAR(50) DEFAULT 'planning',
  total_distance_km NUMERIC(10, 2) DEFAULT 0,
  total_expenses NUMERIC(15, 2) DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.travel_trip_stops (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id BIGINT REFERENCES public.travel_trips(id) ON DELETE CASCADE,
  location_id BIGINT REFERENCES public.travel_locations(id) ON DELETE CASCADE,
  day_number INT DEFAULT 1,
  visit_time VARCHAR(50),
  order_index INT DEFAULT 1,
  transport_mode VARCHAR(50) DEFAULT 'driving',
  stop_notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- 8. BẢNG NHẬT KÝ & ĐÁNH GIÁ (travel_reviews_logs)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.travel_reviews_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id VARCHAR(100),
  user_email VARCHAR(255),
  user_name VARCHAR(255),
  location_id BIGINT REFERENCES public.travel_locations(id) ON DELETE CASCADE,
  visited_at TIMESTAMPTZ DEFAULT NOW(),
  rating NUMERIC(3, 1) DEFAULT 5,
  actual_expense NUMERIC(15, 2) DEFAULT 0,
  review_text TEXT,
  captured_photos JSONB DEFAULT '[]'::jsonb,
  weather VARCHAR(100),
  companion VARCHAR(100),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tự động tương thích ngược: Chuyển đổi captured_photos sang JSONB nếu bảng cũ đang lưu dạng TEXT[] hoặc ARRAY
DO $$ 
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
      AND table_name = 'travel_reviews_logs' 
      AND column_name = 'captured_photos' 
      AND (data_type = 'ARRAY' OR udt_name = '_text' OR udt_name = '_varchar')
  ) THEN
    ALTER TABLE public.travel_reviews_logs 
      ALTER COLUMN captured_photos DROP DEFAULT;
    ALTER TABLE public.travel_reviews_logs 
      ALTER COLUMN captured_photos TYPE JSONB USING COALESCE(to_jsonb(captured_photos), '[]'::jsonb);
    ALTER TABLE public.travel_reviews_logs 
      ALTER COLUMN captured_photos SET DEFAULT '[]'::jsonb;
  END IF;
END $$;

-- -----------------------------------------------------------------------------
-- 9. BẢNG SỔ CHI TIÊU (travel_expenses)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.travel_expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id VARCHAR(100),
  user_email VARCHAR(255),
  user_name VARCHAR(255),
  trip_id BIGINT REFERENCES public.travel_trips(id) ON DELETE SET NULL,
  location_id BIGINT REFERENCES public.travel_locations(id) ON DELETE SET NULL,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(50) DEFAULT 'food',
  amount NUMERIC(15, 2) DEFAULT 0,
  payment_method VARCHAR(50) DEFAULT 'cash',
  receipt_url TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- 10. BẢNG BÁO CÁO SAI SÓT / VI PHẠM (travel_reports)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.travel_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id BIGINT NOT NULL,
  location_name VARCHAR(255) NOT NULL,
  location_address TEXT,
  reported_by_user_id VARCHAR(100),
  reported_by_user_name VARCHAR(255),
  reported_by_user_email VARCHAR(255),
  reason VARCHAR(50) NOT NULL,
  description TEXT NOT NULL,
  proof_url TEXT,
  status VARCHAR(50) DEFAULT 'pending',
  admin_note TEXT,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- 11. BẢNG NHẬT KÝ KIỂM TOÁN (travel_audit_logs)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.travel_audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name VARCHAR(100) NOT NULL,
  record_id VARCHAR(100) NOT NULL,
  action VARCHAR(50) NOT NULL,
  changed_fields JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- 12. VIEW TỔNG HỢP TIỆN DỤNG (travel_places_view)
-- -----------------------------------------------------------------------------
DROP VIEW IF EXISTS public.travel_places_view CASCADE;
CREATE OR REPLACE VIEW public.travel_places_view WITH (security_invoker = on) AS
SELECT
  l.id,
  l.name,
  l.group_id,
  l.group_id AS "group",
  g.name AS group_name,
  g.icon AS group_icon,
  l.city_id,
  c.name AS city_name,
  l.category,
  l.lat,
  l.lng,
  l.address,
  l.phone,
  l.contact,
  l.checked,
  l.visited_at,
  l.is_favorite,
  l.is_deleted,
  l.deleted_at,
  COALESCE(d.rating, 4.8) AS rating,
  COALESCE(d.price_range, ''::character varying) AS price_range,
  COALESCE(d.opening_hours, ''::character varying) AS opening_hours,
  COALESCE(d.best_time_to_visit, ''::character varying) AS best_time_to_visit,
  COALESCE(d.notes, ''::text) AS notes,
  COALESCE(d.travel_tips, ''::text) AS travel_tips,
  COALESCE(d.specialties, ''::text) AS specialties,
  COALESCE(d.thumbnail_url, ''::text) AS thumbnail_url,
  CASE 
    WHEN d.gallery_urls IS NULL THEN '[]'::jsonb 
    ELSE to_jsonb(d.gallery_urls) 
  END AS gallery_urls,
  COALESCE(d.website_url, ''::text) AS website_url,
  (
    SELECT COUNT(*) 
    FROM public.travel_reviews_logs r 
    WHERE r.location_id = l.id
  ) AS reviews_count,
  l.created_at,
  l.updated_at
FROM public.travel_locations l
LEFT JOIN public.travel_location_details d ON l.id = d.location_id
LEFT JOIN public.travel_groups g ON l.group_id::text = g.id::text
LEFT JOIN public.travel_cities c ON l.city_id::text = c.id::text
WHERE l.is_deleted = FALSE;

-- -----------------------------------------------------------------------------
-- 13. CHỈ MỤC TỐI ƯU HIỆU NĂNG TÌM KIẾM
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_travel_locations_city ON public.travel_locations (city_id);
CREATE INDEX IF NOT EXISTS idx_travel_locations_group ON public.travel_locations (group_id);
CREATE INDEX IF NOT EXISTS idx_travel_locations_coords ON public.travel_locations (lat, lng);
CREATE INDEX IF NOT EXISTS idx_travel_locations_deleted ON public.travel_locations (is_deleted);
CREATE INDEX IF NOT EXISTS idx_travel_trips_user ON public.travel_trips (user_id);
CREATE INDEX IF NOT EXISTS idx_travel_reviews_loc ON public.travel_reviews_logs (location_id);
CREATE INDEX IF NOT EXISTS idx_travel_reviews_user ON public.travel_reviews_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_travel_expenses_user ON public.travel_expenses (user_id);
CREATE INDEX IF NOT EXISTS idx_travel_reports_status ON public.travel_reports (status);

-- -----------------------------------------------------------------------------
-- 14. KÍCH HOẠT BẢO MẬT ROW LEVEL SECURITY (RLS) & CHÍNH SÁCH TRUY CẬP
-- -----------------------------------------------------------------------------
ALTER TABLE public.travel_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.travel_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.travel_cities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.travel_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.travel_location_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.travel_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.travel_location_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.travel_trips ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.travel_trip_stops ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.travel_reviews_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.travel_expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.travel_reports ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'travel_users' AND policyname = 'Public Access travel_users') THEN
    CREATE POLICY "Public Access travel_users" ON public.travel_users FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'travel_groups' AND policyname = 'Public Access travel_groups') THEN
    CREATE POLICY "Public Access travel_groups" ON public.travel_groups FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'travel_cities' AND policyname = 'Public Access travel_cities') THEN
    CREATE POLICY "Public Access travel_cities" ON public.travel_cities FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'travel_locations' AND policyname = 'Public Access travel_locations') THEN
    CREATE POLICY "Public Access travel_locations" ON public.travel_locations FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'travel_location_details' AND policyname = 'Public Access travel_location_details') THEN
    CREATE POLICY "Public Access travel_location_details" ON public.travel_location_details FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'travel_tags' AND policyname = 'Public Access travel_tags') THEN
    CREATE POLICY "Public Access travel_tags" ON public.travel_tags FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'travel_location_tags' AND policyname = 'Public Access travel_location_tags') THEN
    CREATE POLICY "Public Access travel_location_tags" ON public.travel_location_tags FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'travel_trips' AND policyname = 'Public Access travel_trips') THEN
    CREATE POLICY "Public Access travel_trips" ON public.travel_trips FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'travel_trip_stops' AND policyname = 'Public Access travel_trip_stops') THEN
    CREATE POLICY "Public Access travel_trip_stops" ON public.travel_trip_stops FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'travel_reviews_logs' AND policyname = 'Public Access travel_reviews_logs') THEN
    CREATE POLICY "Public Access travel_reviews_logs" ON public.travel_reviews_logs FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'travel_expenses' AND policyname = 'Public Access travel_expenses') THEN
    CREATE POLICY "Public Access travel_expenses" ON public.travel_expenses FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'travel_reports' AND policyname = 'Public Access travel_reports') THEN
    CREATE POLICY "Public Access travel_reports" ON public.travel_reports FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;

-- =============================================================================
-- DỮ LIỆU CỐT LÕI KHỞI TẠO (ESSENTIAL SEED DATA)
-- =============================================================================

-- A. TÀI KHOẢN QUẢN TRỊ VIÊN ADMIN DUY NHẤT (Mật khẩu: 0918273645)
DELETE FROM public.travel_users WHERE email IN ('viewer@travelmaps.vn', 'admin@travelmaps.vn', 'user@travelmaps.vn');

INSERT INTO public.travel_users (name, email, password, role, avatar_url, phone, status)
VALUES
  (
    'Trùm',
    'caophuocdanh@hotmail.com',
    '$2b$10$/HY5pREN6kXeyehq8KQtoeZDcvCdQARuAboLwPNLlbmqQSITt6Aay',
    'admin',
    '',
    '0901234567',
    'active'
  )
ON CONFLICT (email) DO UPDATE SET
  name = EXCLUDED.name,
  password = EXCLUDED.password,
  role = EXCLUDED.role,
  avatar_url = EXCLUDED.avatar_url,
  phone = EXCLUDED.phone,
  status = EXCLUDED.status;

-- B. 5 PHÂN NHÓM DỊCH VỤ CƠ BẢN
INSERT INTO public.travel_groups (id, name, icon, badge_bg, marker_color, description, sort_order)
VALUES
  ('du_lich', 'Du lịch & Thắng cảnh', '🏖️', 'bg-emerald-100 text-emerald-800 border-emerald-300', '#059669', 'Danh lam thắng cảnh, di tích lịch sử, bãi biển, núi rừng, điểm check-in sống ảo', 1),
  ('an_uong', 'Ẩm thực & Quán ăn', '🍜', 'bg-amber-100 text-amber-800 border-amber-300', '#d97706', 'Món ăn đặc sản địa phương, nhà hàng, quán ăn ngon, ẩm thực đường phố, cafe', 2),
  ('dich_vu', 'Khách sạn & Tiện ích', '🏨', 'bg-blue-100 text-blue-800 border-blue-300', '#2563eb', 'Khách sạn, Resort, Homestay, trạm xăng, thuê xe, dịch vụ y tế, hỗ trợ du khách', 3),
  ('giai_tri', 'Vui chơi & Giải trí', '🎡', 'bg-purple-100 text-purple-800 border-purple-300', '#9333ea', 'Công viên chủ đề, rạp chiếu phim, bar pub, khu thể thao mạo hiểm, ca nhạc', 4),
  ('khac', 'Khác & Ghi nhớ', '📌', 'bg-slate-100 text-slate-800 border-slate-300', '#475569', 'Các địa điểm cá nhân, điểm hẹn riêng, trạm dừng chân tạm thời', 5)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  icon = EXCLUDED.icon,
  badge_bg = EXCLUDED.badge_bg,
  marker_color = EXCLUDED.marker_color,
  description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order;

-- C. DANH MỤC 7 THẺ GẮN TAGS CƠ BẢN
INSERT INTO public.travel_tags (id, name, color, icon)
VALUES
  ('song_ao', 'Sống Ảo / Check-in', 'pink', '📸'),
  ('dac_san', 'Đặc Sản Địa Phương', 'amber', '🍲'),
  ('view_hoang_hon', 'View Hoàng Hôn', 'orange', '🌅'),
  ('gia_dinh', 'Thích Hợp Gia Đình', 'blue', '👨‍👩‍👧‍👦'),
  ('michelin', 'Michelin Selected', 'red', '⭐'),
  ('view_bien', 'View Biển / View Hồ', 'cyan', '🌊'),
  ('gia_binh_dan', 'Giá Bình Dân', 'emerald', '💵')
ON CONFLICT (id) DO NOTHING;

-- D. ĐẦY ĐỦ 63 TỈNH THÀNH / THÀNH PHỐ TOÀN QUỐC VIỆT NAM
INSERT INTO public.travel_cities (id, name, code, lat, lng, sort_order)
VALUES
  ('ha_noi', 'Hà Nội', 'HAN', 21.02850062, 105.85424640, 1),
  ('hai_phong', 'Hải Phòng', 'HPH', 20.84497262, 106.68817088, 2),
  ('quang_ninh', 'Quảng Ninh / Hạ Long', 'VHL', 20.95422682, 107.08339666, 3),
  ('lao_cai', 'Lào Cai / Sa Pa', 'SAP', 22.48567680, 103.97078686, 4),
  ('ninh_binh', 'Ninh Bình', 'NBH', 20.25069608, 105.97443640, 5),
  ('ha_giang', 'Hà Giang', 'HGI', 22.82336260, 104.98395840, 6),
  ('cao_bang', 'Cao Bằng', 'CBG', 22.66572420, 105.97397602, 7),
  ('yen_bai', 'Yên Bái', 'YBI', 21.70544000, 104.87540806, 8),
  ('dien_bien', 'Điện Biên', 'DBN', 21.38611664, 103.02317266, 9),
  ('vinh_phuc', 'Vĩnh Phúc', 'VPC', 21.30891466, 105.60470048, 10),
  ('bac_giang', 'Bắc Giang', 'BGG', 21.27316406, 106.19464864, 11),
  ('bac_kan', 'Bắc Kạn', 'BKN', 22.14756222, 105.83486246, 12),
  ('bac_ninh', 'Bắc Ninh', 'BNH', 21.18619286, 106.07634428, 13),
  ('ha_nam', 'Hà Nam', 'HNM', 20.54520844, 105.91223402, 14),
  ('hai_duong', 'Hải Dương', 'HDG', 20.93648624, 106.31554260, 15),
  ('hoa_binh', 'Hòa Bình', 'HBH', 20.81337262, 105.33838880, 16),
  ('hung_yen', 'Hưng Yên', 'HYN', 20.64648820, 106.05111060, 17),
  ('lai_chau', 'Lai Châu', 'LCU', 22.39646248, 103.45893088, 18),
  ('lang_son', 'Lạng Sơn', 'LSN', 21.85338866, 106.76113200, 19),
  ('nam_dinh', 'Nam Định', 'NDH', 20.43337444, 106.18337466, 20),
  ('phu_tho', 'Phú Thọ', 'PTO', 21.32280442, 105.21556084, 21),
  ('son_la', 'Sơn La', 'SLA', 21.32569008, 103.91890844, 22),
  ('thai_binh', 'Thái Bình', 'TBH', 20.45946240, 106.33338206, 23),
  ('thai_nguyen', 'Thái Nguyên', 'TNN', 21.59289848, 105.84421042, 24),
  ('tuyen_quang', 'Tuyên Quang', 'TQG', 21.82399262, 105.21581084, 25),
  ('da_nang', 'Đà Nẵng', 'DAD', 16.05442068, 108.20220446, 26),
  ('quang_nam', 'Quảng Nam / Hội An', 'VNHAN', 15.88011204, 108.33842248, 27),
  ('thua_thien_hue', 'Thừa Thiên Huế', 'HUI', 16.46371666, 107.59096842, 28),
  ('khanh_hoa', 'Khánh Hòa / Nha Trang', 'NHA', 12.23888040, 109.19674266, 29),
  ('lam_dong', 'Lâm Đồng / Đà Lạt', 'DLI', 11.94045444, 108.45836488, 30),
  ('quang_binh', 'Quảng Bình', 'QBH', 17.46864060, 106.62226668, 31),
  ('quang_tri', 'Quảng Trị', 'QTI', 16.75108222, 107.18332848, 32),
  ('quang_ngai', 'Quảng Ngãi', 'QNI', 15.12106844, 108.80082628, 33),
  ('binh_dinh', 'Bình Định / Quy Nhơn', 'BDH', 13.78396204, 109.21976800, 34),
  ('phu_yen', 'Phú Yên', 'PYU', 13.08831484, 109.29257008, 35),
  ('ninh_thuan', 'Ninh Thuận', 'NTH', 11.56674822, 108.98333204, 36),
  ('binh_thuan', 'Bình Thuận / Phan Thiết', 'BTN', 10.93337604, 108.19268868, 37),
  ('thanh_hoa', 'Thanh Hóa', 'THA', 19.83048062, 105.76671806, 38),
  ('nghe_an', 'Nghệ An', 'NAN', 18.67330428, 105.68115824, 39),
  ('ha_tinh', 'Hà Tĩnh', 'HTH', 18.34382468, 105.90587602, 40),
  ('kon_tum', 'Kon Tum', 'KTM', 14.35126486, 108.02284444, 41),
  ('gia_lai', 'Gia Lai', 'GLAI', 13.98339840, 108.02284444, 42),
  ('dak_lak', 'Đắk Lắk', 'DLK', 12.66672046, 108.05964662, 43),
  ('dak_nong', 'Đắk Nông', '', 12.00425822, 107.68755644, 44),
  ('ho_chi_minh', 'TP. Hồ Chí Minh', 'SGN', 10.82319022, 106.62974800, 45),
  ('can_tho', 'Cần Thơ', 'VCA', 10.04524242, 105.74699802, 46),
  ('ba_ria_vung_tau', 'Bà Rịa - Vũng Tàu', 'VTG', 10.34678282, 107.08436820, 47),
  ('kien_giang', 'Kiên Giang / Phú Quốc', 'PQC', 10.01253880, 105.08090422, 48),
  ('an_giang', 'An Giang', 'AGG', 10.53814626, 105.12596448, 49),
  ('bac_lieu', 'Bạc Liêu', 'BLU', 9.29410202, 105.72440064, 50),
  ('ben_tre', 'Bến Tre', 'BTE', 10.24324282, 106.37518424, 51),
  ('binh_duong', 'Bình Dương', 'BDG', 11.16043826, 106.65232264, 52),
  ('binh_phuoc', 'Bình Phước', 'BPC', 11.64734648, 106.89258688, 53),
  ('ca_mau', 'Cà Mau', 'CMU', 9.17695646, 105.15245244, 54),
  ('dong_nai', 'Đồng Nai', 'DNI', 10.94564240, 106.82471420, 55),
  ('dong_thap', 'Đồng Tháp', 'DTP', 10.49385000, 105.68812228, 56),
  ('hau_giang', 'Hậu Giang', 'HGI2', 9.78429804, 105.47011206, 57),
  ('long_an', 'Long An', 'LAN', 10.53625460, 106.40862286, 58),
  ('soc_trang', 'Sóc Trăng', 'STG', 9.60338402, 105.98660408, 59),
  ('tay_ninh', 'Tây Ninh', 'TNI', 11.31288066, 106.09832260, 60),
  ('tien_giang', 'Tiền Giang', 'TGG', 10.42830060, 106.34081624, 61),
  ('tra_vinh', 'Trà Vinh', 'TVH', 9.93479224, 106.34535884, 62),
  ('vinh_long', 'Vĩnh Long', 'VLG', 10.25361260, 105.97229804, 63),
  ('hoi_an', 'Hội An', 'HOI', 15.88011204, 108.33842248, 64),
  ('sa_pa', 'Sa Pa', 'SAP', 22.33640808, 103.84386824, 65),
  ('phu_quoc', 'Phú Quốc', 'PQC', 10.28997640, 103.98422446, 66),
  ('hue', 'Huế', 'HUE', 16.46371666, 107.59096842, 67)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  code = EXCLUDED.code,
  lat = EXCLUDED.lat,
  lng = EXCLUDED.lng,
  sort_order = EXCLUDED.sort_order;
`;

export const SQL_SAMPLE_SCRIPT = CREATE_TABLE_SQL;
